### ISSUE TITLE
pyqt5中文乱码问题 

### ISSUE THREAD

**Issue by bewithme** [HollowMan6/docker-pyqt5-spiders#1]
经测试pyqt5组件可以显示中文，请问是哪个部份修复了pyqt5中文乱码问题？

**Comment by HollowMan6** [comment]
具体不太清楚你的情况，我认为只要支持中文的字体安装到位：https://github.com/HollowMan6/docker-pyqt5-spiders/blob/master/Dockerfile#L33 应该就差不多了
